pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'aws --version'
                sh 'aws s3 ls'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}