pipeline {
    agent any

    stages {
        stage('Build') {
            environment {
                S3_BUCKET = 's3'
            }
            steps {
                sh 'aws --version'
                sh 'aws s3 ls'
                sh 'sh container/build_and_push.sh'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}