pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                python --version
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}